<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.cy.micoservice.app</groupId>
		<artifactId>system</artifactId>
		<version>1.0.0</version>
	</parent>
	
	<artifactId>app-framework-parent</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>
	
	<modules>
		<module>app-framework-cache-starter</module>
		<module>app-framework-minio-starter</module>
		<module>app-framework-mybatis-starter</module>
		<module>app-framework-dubbo-starter</module>
		<module>app-framework-web-starter</module>
		<module>app-framework-identify-starter</module>
		<module>app-framework-rocketmq-starter</module>
		<module>app-framework-kafka-starter</module>
		<module>app-framework-id-starter</module>
		<module>app-framework-elasticsearch-starter</module>
		<module>app-framework-sharding-jdbc-starter</module>
		<module>app-framework-opentelemetry-starter</module>
	</modules>
	
	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	
<!--	<build>
		<plugins>
			&lt;!&ndash;
						1.自Maven 3.5.0-beta-1 开始，可以使用 ${revision}, ${sha1} and/or ${changelist} 这样的变量作为版本占位符
						2.但是在install或者deploy是无法识别的，就需要这个插件：发现使用插件之后，发现它是把这个新的pom打到jar包里。也就是说，
							这个插件的作用就是在install或者deploy的时候，生成一个新的替换占位符的pom文件，也就是帮你替换了这些变量，接着把新的pom文件打入到jar包里。
						 &ndash;&gt;
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
				<version>1.1.0</version>
				<configuration>
					<updatePomFile>true</updatePomFile>
					<flattenMode>resolveCiFriendliesOnly</flattenMode>
				</configuration>
				<executions>
					<execution>
						<id>flatten</id>
						<phase>process-resources</phase>
						<goals>
							<goal>flatten</goal>
						</goals>
					</execution>
					<execution>
						<id>flatten.clean</id>
						<phase>clean</phase>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>-->
</project>